// PagmoNet4j.ipopt is a SELF-CONTAINED SUPERSET of PagmoNet4j (the Java twin of
// Pagmo.NET.Ipopt). SWIG regenerates the entire binding surface as one unit, so an
// IPOPT-enabled artifact necessarily redefines every type the base artifact defines.
// There is therefore no way to layer IPOPT on top of a *published* pagmonet4j jar
// (that was the old, broken add-on design that shoved the IPOPT native into the base
// jar at CI time and broke for real consumers).
//
// Instead this project compiles the base PagmoNet4j Java sources (from the PagmoNet4j
// submodule) together with the IPOPT-enabled SWIG bindings (regenerated into
// src/generated/java by CI) into a single jar, and bundles its own IPOPT-enabled
// native library plus its full dynamic dependency closure. Consumers depend on EITHER
// pagmonet4j OR pagmonet4j-ipopt, never both — a Gradle capability conflict (declared
// below) enforces that, the same way `groovy` and `groovy-all` are kept exclusive.

plugins {
    java
    `maven-publish`
}

// group + version are single-sourced from gradle.properties (CI overrides version with
// -Pversion=<tag>); do not hardcode them here.

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
    withJavadocJar()
}

// Name the jar after the published artifactId (default would be the project name,
// "PagmoNet4j.ipopt"); keeps build/libs/*.jar consistent with the Maven coordinate.
base {
    archivesName.set("pagmonet4j-ipopt")
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            // Base hand-written ergonomic layer (ManagedProblemBase, NativeLoader,
            // adapters, …) compiled directly in from the submodule — NOT the base's
            // generated bindings (those would duplicate the IPOPT superset below).
            srcDir("PagmoNet4j/core/src/main/java")
            // The full IPOPT-enabled SWIG surface (all proxies + the superset JNI
            // intrinsic class + ipopt), regenerated by CI with -DPAGMO_WITH_IPOPT_JNI.
            srcDir("src/generated/java")
        }
    }
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.11.3"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// ── Capability conflict: pagmonet4j-ipopt is a drop-in replacement for pagmonet4j ──
// Declaring that this module ALSO provides the `pagmonet4j` capability makes Gradle
// fail any consumer graph that pulls in both, forcing a single choice. Declaring an
// explicit capability drops the implicit one, so we re-declare the natural
// pagmonet4j-ipopt capability too.
listOf("apiElements", "runtimeElements").forEach { cfg ->
    configurations.findByName(cfg)?.outgoing {
        capability("${project.group}:pagmonet4j-ipopt:${project.version}")
        capability("${project.group}:pagmonet4j:${project.version}")
    }
}

// ── Native packaging ──────────────────────────────────────────────────────────────
// CI stages each platform's self-contained native closure (wrapper + bundled deps,
// produced by scripts/bundle-native-deps.ps1) under staged-natives/<rid>/. Bundle each
// into the jar at natives/<rid>/ so NativeLoader can extract the whole closure at
// runtime with no PAGMO4J_NATIVE_DIR / java.library.path. Builds without staged natives
// still produce a (non-self-contained) jar so local dev/test works via the env var.
tasks.processResources {
    val stagedNatives = rootProject.projectDir.resolve("staged-natives")
    if (stagedNatives.isDirectory) {
        stagedNatives.listFiles()?.filter { it.isDirectory }?.forEach { ridDir ->
            from(ridDir) { into("natives/${ridDir.name}") }
        }
    }
}

// Base sources and generated sources can contribute the same package paths.
tasks.named<Jar>("sourcesJar") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// SWIG-generated code has missing @param/@return tags — suppress doclint so javadoc doesn't fail.
tasks.javadoc {
    (options as StandardJavadocDocletOptions).addStringOption("Xdoclint:none", "-quiet")
}

tasks.test {
    useJUnitPlatform()
    val nativeDir = System.getenv("PAGMO4J_NATIVE_DIR")
        ?.let { rootProject.projectDir.resolve(it).absolutePath }
        ?: "."
    systemProperty("java.library.path", nativeDir)
    forkEvery = 1
    maxParallelForks = 1
    systemProperty("junit.jupiter.execution.timeout.default", "30s")
}

publishing {
    repositories {
        mavenLocal()
        // File-based repo the CI clean-room job consumes to prove the published-shaped
        // artifact works on a machine with no dev tools, no conda, no native env hints.
        maven {
            name = "BuildLocal"
            url = layout.buildDirectory.dir("localrepo").get().asFile.toURI()
        }
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/samthegliderpilot/PagmoNet4j.ipopt")
            credentials {
                username = System.getenv("GITHUB_ACTOR") ?: ""
                password = System.getenv("GITHUB_TOKEN") ?: ""
            }
        }
    }
    publications {
        create<MavenPublication>("maven") {
            artifactId = "pagmonet4j-ipopt"
            from(components["java"])
            pom {
                name.set("pagmonet4j-ipopt")
                description.set("PagmoNet4j with the IPOPT (Interior Point OPTimizer) nonlinear solver bundled. Drop-in superset of pagmonet4j — depend on this OR pagmonet4j, not both.")
                url.set("https://github.com/samthegliderpilot/PagmoNet4j.ipopt")
                licenses {
                    license {
                        name.set("LGPL-2.1-or-later")
                        url.set("https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html")
                    }
                }
                developers {
                    developer {
                        id.set("samthegliderpilot")
                        name.set("samthegliderpilot")
                        email.set("samthegliderpilot@gmail.com")
                    }
                }
                scm {
                    url.set("https://github.com/samthegliderpilot/PagmoNet4j.ipopt")
                    connection.set("scm:git:git://github.com/samthegliderpilot/PagmoNet4j.ipopt.git")
                    developerConnection.set("scm:git:ssh://github.com/samthegliderpilot/PagmoNet4j.ipopt.git")
                }
                issueManagement {
                    system.set("GitHub")
                    url.set("https://github.com/samthegliderpilot/PagmoNet4j.ipopt/issues")
                }
            }
        }
    }
}
